name: Version and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.event.inputs.version }}
      NAME: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Increment Version
        run: |
          git config --global user.name 'Frontmatter Actions'
          git config --global user.email 'actions@frontmatter.ai'
          
          echo -n ${VERSION} > version
          python3 update_version.py ${VERSION}
          
          rm -f hct.tapp
          zip -0 -r -j hct.tapp module/*
          
          git add version
          git add module/hct.be
          git add README.md
          git add hct.tapp
          
          git commit -am "Increment version number to ${VERSION} for release"
          git push          
          git tag -a v${VERSION} -m "Release version ${VERSION}"
          
          git checkout --track origin/release
          git rebase master
          
          git push --follow-tags

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hct.tapp
          tag_name: v${{ github.event.inputs.version }}
          generate_release_notes: true
